### ISSUE TITLE
Executing BlockPurging -> stats results in AttributeError

### ISSUE THREAD

**Issue by mrckzgl** [AI-team-UoA/pyJedAI#19]
Consider following example code
```
data = Data(
    dataset_1=d1,
    id_column_name_1='id',
    ground_truth=gt,
    attributes_1=attr
)
bb = QGramsBlocking()
blocks = bb.build_blocks(data)
bp = BlockPurging()
blocks = bp.process(blocks, data, tqdm_disable=False)
bp.stats(blocks)
```

This results in:
```
Traceback (most recent call last):
  File "[REDACTED]/jedi_er.py", line 43, in <module>
    bp.stats(blocks)
  File "[REDACTED]/.local/lib/python3.10/site-packages/pyjedai/block_building.py", line 181, in stats
    "\n\tNumber of blocks dropped: " + str(self.num_of_blocks_dropped) +
AttributeError: 'BlockPurging' object has no attribute 'num_of_blocks_dropped'
```

best

**Comment by Nikoletos-K** [comment]
It has been corrected at dev-stage and will be published in the next release.

Thanks for the feedback!

**Comment by Nikoletos-K** [comment]
It has been fixed in the new release.

Cheers,
Konstantinos
